In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dataset=pd.read_csv('/content/drive/MyDrive/Train.csv')

In [ ]:
dataset

Item_Identifier  Item_Weight  ...        Outlet_Type  Item_Outlet_Sales
0              FDA15        9.300  ...  Supermarket Type1          3735.1380
1              DRC01        5.920  ...  Supermarket Type2           443.4228
2              FDN15       17.500  ...  Supermarket Type1          2097.2700
3              FDX07       19.200  ...      Grocery Store           732.3800
4              NCD19        8.930  ...  Supermarket Type1           994.7052
...              ...          ...  ...                ...                ...
8518           FDF22        6.865  ...  Supermarket Type1          2778.3834
8519           FDS36        8.380  ...  Supermarket Type1           549.2850
8520           NCJ29       10.600  ...  Supermarket Type1          1193.1136
8521           FDN46        7.210  ...  Supermarket Type2          1845.5976
8522           DRG01       14.800  ...  Supermarket Type1           765.6700

[8523 rows x 12 columns]

In [ ]:
dataset.info

<bound method DataFrame.info of      Item_Identifier  Item_Weight  ...        Outlet_Type  Item_Outlet_Sales
0              FDA15        9.300  ...  Supermarket Type1          3735.1380
1              DRC01        5.920  ...  Supermarket Type2           443.4228
2              FDN15       17.500  ...  Supermarket Type1          2097.2700
3              FDX07       19.200  ...      Grocery Store           732.3800
4              NCD19        8.930  ...  Supermarket Type1           994.7052
...              ...          ...  ...                ...                ...
8518           FDF22        6.865  ...  Supermarket Type1          2778.3834
8519           FDS36        8.380  ...  Supermarket Type1           549.2850
8520           NCJ29       10.600  ...  Supermarket Type1          1193.1136
8521           FDN46        7.210  ...  Supermarket Type2          1845.5976
8522           DRG01       14.800  ...  Supermarket Type1           765.6700

[8523 rows x 12 columns]>

In [ ]:
dataset.isnull().any()

Item_Identifier              False
Item_Weight                   True
Item_Fat_Content             False
Item_Visibility              False
Item_Type                    False
Item_MRP                     False
Outlet_Identifier            False
Outlet_Establishment_Year    False
Outlet_Size                   True
Outlet_Location_Type         False
Outlet_Type                  False
Item_Outlet_Sales            False
dtype: bool

In [ ]:
dataset.isnull().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [ ]:
dataset["Item_Weight"].fillna(dataset["Item_Weight"].mean(),inplace = True)

In [ ]:
dataset["Outlet_Size"].fillna(dataset["Outlet_Size"].mode()[0],inplace=True)

In [ ]:
dataset.isnull().any()

Item_Identifier              False
Item_Weight                  False
Item_Fat_Content             False
Item_Visibility              False
Item_Type                    False
Item_MRP                     False
Outlet_Identifier            False
Outlet_Establishment_Year    False
Outlet_Size                  False
Outlet_Location_Type         False
Outlet_Type                  False
Item_Outlet_Sales            False
dtype: bool

In [ ]:
x = dataset.iloc[:,0:11].values
x

array([['FDA15', 9.3, 'Low Fat', ..., 'Medium', 'Tier 1',
        'Supermarket Type1'],
       ['DRC01', 5.92, 'Regular', ..., 'Medium', 'Tier 3',
        'Supermarket Type2'],
       ['FDN15', 17.5, 'Low Fat', ..., 'Medium', 'Tier 1',
        'Supermarket Type1'],
       ...,
       ['NCJ29', 10.6, 'Low Fat', ..., 'Small', 'Tier 2',
        'Supermarket Type1'],
       ['FDN46', 7.21, 'Regular', ..., 'Medium', 'Tier 3',
        'Supermarket Type2'],
       ['DRG01', 14.8, 'Low Fat', ..., 'Small', 'Tier 1',
        'Supermarket Type1']], dtype=object)

In [ ]:
y = dataset.iloc[:,11:12].values
y

array([[3735.138 ],
       [ 443.4228],
       [2097.27  ],
       ...,
       [1193.1136],
       [1845.5976],
       [ 765.67  ]])

In [ ]:
x.shape

(8523, 11)

In [ ]:
y.shape

(8523, 1)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ct = ColumnTransformer([("one",OneHotEncoder(),[0,2,4,6,8,9,10])],remainder = "passthrough")
x = ct.fit_transform(x)

In [ ]:
x=x.toarray()
x

AttributeError: ignored

In [ ]:
x.shape

(8523, 1604)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state = 0)

In [ ]:
from sklearn.linear_model import LinearRegression
mlr = LinearRegression()
mlr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
y_pred = mlr.predict(x_test)

In [ ]:
y_pred

array([[ 2131.75488801],
       [ 3272.63130497],
       [ 2393.49579762],
       ...,
       [ 4829.06863781],
       [-1046.07415422],
       [ 5645.33881776]])

In [ ]:
y_test

array([[1426.1436],
       [1201.769 ],
       [1836.2764],
       ...,
       [2885.5772],
       [ 218.3824],
       [5478.2024]])

In [ ]:
from sklearn.metrics import r2_score
accuracy = r2_score(y_pred,y_test)

In [ ]:
accuracy

0.14420971691855355

In [ ]:
y_p = mlr.predict(ct.transform(([["DRG01",14.8,"Low Fat",0.044878,"Soft Drinks",75.4670,"OUT046",1997,"Small","Tier 1","Supermarket Type1"]])))

In [ ]:
y_p

array([[1427.18988559]])