In [93]:
#KNN Regressor
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
dataset=pd.read_csv('/content/Wind Power.csv')
dataset

DateTime  ...  Power generated by system | (kW)
0    2007-01-01 00:00:00  ...                          33688.10
1    2007-01-01 01:00:00  ...                          37261.90
2    2007-01-01 02:00:00  ...                          30502.90
3    2007-01-01 03:00:00  ...                          28419.20
4    2007-01-01 04:00:00  ...                          27370.30
..                   ...  ...                               ...
395  2011-05-04 13:00:00  ...                          10562.60
396  2011-05-04 14:00:00  ...                           4757.80
397  2011-05-04 15:00:00  ...                          10007.70
398  2011-05-04 16:00:00  ...                           3212.14
399  2011-05-04 17:00:00  ...                           1382.99

[400 rows x 6 columns]

In [94]:
dataset.head()

DateTime  ...  Power generated by system | (kW)
0  2007-01-01 00:00:00  ...                           33688.1
1  2007-01-01 01:00:00  ...                           37261.9
2  2007-01-01 02:00:00  ...                           30502.9
3  2007-01-01 03:00:00  ...                           28419.2
4  2007-01-01 04:00:00  ...                           27370.3

[5 rows x 6 columns]

In [95]:
dataset.isnull().any()

DateTime                            False
Air temperature | ('C)              False
Pressure | (atm)                    False
Wind speed | (m/s)                  False
Wind direction | (deg)              False
Power generated by system | (kW)    False
dtype: bool

In [96]:
x = dataset.iloc[:,1:5].values
y = dataset.iloc[:,5:6].values

In [97]:
x

array([[ 10.926   ,   0.979103,   9.014   , 229.      ],
       [  9.919   ,   0.979566,   9.428   , 232.      ],
       [  8.567   ,   0.979937,   8.7     , 236.      ],
       ...,
       [ 22.504   ,   0.983913,   6.26    , 151.      ],
       [ 22.064   ,   0.983861,   4.77    , 149.      ],
       [ 23.416   ,   0.983793,   4.03    , 179.      ]])

In [98]:
y

array([[33688.1  ],
       [37261.9  ],
       [30502.9  ],
       [28419.2  ],
       [27370.3  ],
       [25805.9  ],
       [11546.8  ],
       [ 8360.76 ],
       [ 6426.64 ],
       [ 9349.45 ],
       [18613.6  ],
       [35381.1  ],
       [17331.5  ],
       [19872.3  ],
       [ 8190.46 ],
       [ 8731.8  ],
       [ 8578.77 ],
       [11030.   ],
       [11088.4  ],
       [11220.2  ],
       [14693.1  ],
       [15064.7  ],
       [16247.5  ],
       [34740.   ],
       [35393.6  ],
       [35278.4  ],
       [43582.8  ],
       [42341.5  ],
       [40346.7  ],
       [42258.8  ],
       [45569.9  ],
       [41616.2  ],
       [42978.3  ],
       [41306.6  ],
       [39903.5  ],
       [40564.3  ],
       [42862.8  ],
       [37064.6  ],
       [16051.8  ],
       [ 4926.84 ],
       [ 1303.4  ],
       [  995.606],
       [ 1661.72 ],
       [ 3060.72 ],
       [11354.7  ],
       [14369.1  ],
       [21278.5  ],
       [34753.3  ],
       [45895.2  ],
       [34225.7  ],


In [99]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
print (x_train.shape)
print (x_test.shape)
print (y_train.shape)
print (y_test.shape)

(320, 4)
(80, 4)
(320, 1)
(80, 1)


In [100]:
x_train

array([[  0.508   ,   0.992628,   7.806   , 344.      ],
       [  8.479   ,   0.988598,   5.525   , 163.      ],
       [  1.937   ,   0.992169,   8.901   , 134.      ],
       ...,
       [  9.268   ,   0.976694,   4.315   , 246.      ],
       [  0.724   ,   0.990834,   8.96    , 130.      ],
       [  2.194   ,   0.985928,   9.996   , 248.      ]])

In [101]:
y_train

array([[22987.8  ],
       [ 6631.76 ],
       [34052.8  ],
       [36938.2  ],
       [42436.   ],
       [58409.9  ],
       [15645.9  ],
       [  690.843],
       [10562.6  ],
       [26802.8  ],
       [ 9404.37 ],
       [52501.6  ],
       [17701.6  ],
       [ 6426.64 ],
       [46645.2  ],
       [19533.4  ],
       [14449.3  ],
       [ 8049.89 ],
       [18899.7  ],
       [20529.9  ],
       [39859.3  ],
       [ 3889.15 ],
       [13386.3  ],
       [21496.   ],
       [23077.9  ],
       [26253.2  ],
       [ 2207.77 ],
       [ 2475.59 ],
       [26663.1  ],
       [16576.1  ],
       [41238.4  ],
       [28244.2  ],
       [21705.6  ],
       [15064.7  ],
       [25060.5  ],
       [25574.3  ],
       [38270.6  ],
       [34225.7  ],
       [57960.7  ],
       [27757.7  ],
       [27498.2  ],
       [30955.6  ],
       [55546.7  ],
       [57964.2  ],
       [ 3490.82 ],
       [16729.1  ],
       [16247.5  ],
       [48092.2  ],
       [ 1860.49 ],
       [16885.8  ],


In [102]:
from sklearn import neighbors
from sklearn.metrics import mean_squared_error 
from math import sqrt
import matplotlib.pyplot as plt
%matplotlib inline

In [110]:
model = neighbors.KNeighborsRegressor(n_neighbors = 5)

model.fit(x_train,y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                    weights='uniform')

In [111]:
y_pred = model.predict(x_test)
y_pred

array([[21787.368 ],
       [24988.38  ],
       [27137.74  ],
       [40306.22  ],
       [21067.51  ],
       [ 9760.596 ],
       [27989.3402],
       [34266.34  ],
       [ 9198.382 ],
       [38914.78  ],
       [28861.848 ],
       [13091.836 ],
       [18870.358 ],
       [ 3960.36  ],
       [22712.268 ],
       [ 7804.57  ],
       [10873.18  ],
       [31554.18  ],
       [34776.4   ],
       [27137.74  ],
       [42159.96  ],
       [15520.012 ],
       [10314.9556],
       [33608.48  ],
       [35539.42  ],
       [13327.4   ],
       [12881.174 ],
       [11501.556 ],
       [19361.018 ],
       [28500.36  ],
       [38378.74  ],
       [30463.6   ],
       [24565.14  ],
       [51604.58  ],
       [26885.76  ],
       [11742.57  ],
       [28500.36  ],
       [38378.74  ],
       [40035.84  ],
       [ 8959.238 ],
       [21115.102 ],
       [15141.148 ],
       [ 9939.836 ],
       [18913.832 ],
       [23370.66  ],
       [34699.32  ],
       [10581.6586],
       [44703

In [112]:
y_test

array([[29237.2 ],
       [12349.2 ],
       [27504.6 ],
       [51597.8 ],
       [18919.8 ],
       [ 1265.36],
       [34144.2 ],
       [35811.4 ],
       [41215.1 ],
       [49593.6 ],
       [37064.6 ],
       [21020.6 ],
       [20704.7 ],
       [ 2469.7 ],
       [17331.5 ],
       [ 2193.34],
       [14806.3 ],
       [20290.7 ],
       [30259.9 ],
       [38782.3 ],
       [27934.  ],
       [18784.1 ],
       [ 2474.38],
       [40584.7 ],
       [35963.2 ],
       [11007.9 ],
       [12810.  ],
       [ 8731.8 ],
       [12336.9 ],
       [39428.1 ],
       [27926.  ],
       [52465.5 ],
       [18661.7 ],
       [49050.2 ],
       [15134.  ],
       [11500.  ],
       [35604.4 ],
       [43987.8 ],
       [53269.7 ],
       [ 1382.99],
       [33509.9 ],
       [11861.6 ],
       [11546.8 ],
       [37261.9 ],
       [19769.5 ],
       [34109.2 ],
       [ 4130.26],
       [44175.3 ],
       [23954.4 ],
       [56073.3 ],
       [17173.6 ],
       [ 4369.96],
       [1211

In [113]:
y_pred[1:5]

array([[24988.38],
       [27137.74],
       [40306.22],
       [21067.51]])

In [114]:
y_test[1:5]

array([[12349.2],
       [27504.6],
       [51597.8],
       [18919.8]])

In [108]:
from sklearn.model_selection import GridSearchCV
params = {'n_neighbors':[2,3,4,5,6,7,8,9]}

knn = neighbors.KNeighborsRegressor()

model = GridSearchCV(knn, params, cv=5)
model.fit(x,y)
model.best_params_

{'n_neighbors': 5}

In [115]:
from sklearn.metrics import r2_score
accuracy = r2_score(y_pred,y_test)
accuracy

0.360873630436521

In [116]:
from sklearn.svm import SVR

In [117]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
sc_y=StandardScaler()
x_train=sc_x.fit_transform(x_train)
y_train=y_train.reshape(len(y_train),1)
y_train=sc_y.fit_transform(y_train)

In [118]:
regressor = SVR(kernel='rbf')
regressor.fit(x_train,y_train)


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [119]:
y_pred = sc_y.inverse_transform(regressor.predict(sc_x.transform(x_test)))
y_pred

array([28810.96834685, 11462.34383245, 28641.74475972, 50737.46233735,
       19003.26773016,  2896.31670901, 33053.69187297, 36169.81386216,
       41270.51847123, 47622.90371753, 37918.44944996, 20691.526448  ,
       20739.99406364,  1502.95023618, 17740.72320067,  2642.14121082,
       14871.44347493, 20125.71614637, 31320.53442413, 39014.23297792,
       28364.01984366, 19355.01546254,  1428.19411581, 38644.25609254,
       36253.37307629, 10191.00443734, 12080.74957892,  7385.40802445,
       11705.22667803, 38126.98129783, 28403.40047395, 51030.12065059,
       19862.45217662, 50522.59115487, 14147.30183944, 10341.81388626,
       37426.53012775, 44546.30929439, 49579.47592213,  1762.49706801,
       32768.11361156, 11798.57763061, 12078.11558628, 37268.20581305,
       19449.65423723, 34681.79784949,  4171.09956183, 44647.76640268,
       24686.39669703, 55349.9785773 , 17201.75048722,  4811.74594146,
       12190.41529233, 44910.63064265, 25069.47022015,  5800.57027432,
      

In [120]:
y_pred[1:5]

array([11462.34383245, 28641.74475972, 50737.46233735, 19003.26773016])

In [121]:
y_test[1:5]

array([[12349.2],
       [27504.6],
       [51597.8],
       [18919.8]])

In [122]:
from sklearn.metrics import r2_score
accuracy = r2_score(y_pred,y_test)
accuracy

0.9954905419685683